# Definition of supported/accepted key algorithms
# This is used as option list for key generation
# as well as validation list for uploaded keys
# If you prefix a value with an underscore, is is accepted for validation
# but not presented on key generation
# The frontend will prefix all values with I18N_OPENXPKI_UI_KEY_XX_YY
# where XX is the key and yy is the value, so if you add new items make sure
# you also add a translation for it.
key:
    # Supported key algorithms (details need to be defined below!)
    alg:
      - ec

    # Supported encryption algorithms (as taken by openssl)
    enc:
      - aes256

    # one of escrow, server, client, both
    # escrow is not implemented in workflows, yet!
    generate: both

    ec:
        # those names are used for validation and to render the
        # option lit when server key generation is allowed
        # The preset is the recommended list from RFC5480
        # The possbile "named" curves are limited by the ones supported
        # by Crypt::PKCS10 at the moment. For NIST P-192/256 you can use
        # either the secpXXXr1 or primeXXXv1 alias
        curve_name:
          - secp384r1
          - secp521r1

        # Curves imply key lengths, setting key length here makes only
        # sense if you do NOT set curve names and want to allow all
        # ecc curves that provided a key length. Note this is the REAL
        # number of key bits, not the nominal security bits value!
        # Always set this with an underscore to hide the key lenght from the
        # key generation parameters dialog (it does not make sense there)
        # key_length:
        #  - _192
        #  - _256

    # I18N_OPENXPKI_UI_KEY_ALG_GOST94
#    gost94:
    # I18N_OPENXPKI_UI_KEY_ALG_GOST2001
#    gost2001:


validity:
    notafter: +01

digest: sha512
increasing_serials: 1
randomized_serial_bytes: 8


publish:
  - queue
  - disk

# Profile extensions - set 0/1 as needed
extensions:
    copy: copy

    basic_constraints:
        critical: 1
        ca: 0

    subject_key_identifier:
        critical: 0
        hash: 1

    authority_key_identifier:
        critical: 0
        keyid:  1
        issuer: 1

    issuer_alt_name:
        critical: 0
        # If the issuer has no subject alternative name, copying returns
        # an empty extension, which is problematic with both RSA SecurId
        # tokens and Cisco devices!
        copy: 1

    crl_distribution_points:
        critical: 0
        uri:
            - http://teleop.roboauto.cz/crl/gw-car/[% ISSUER.CN.0 %].pem
       #     - ldap://teleop.roboauto.cz/[% ISSUER.DN %]

    authority_info_access:
        critical: 0
        ca_issuers: http://teleop.roboauto.cz/ca/gw-car/issuer.pem
        ocsp: http://teleop.roboauto.cz:9876


# I18N Placeholders for key settings
# I18N_OPENXPKI_UI_KEY_ALG
# I18N_OPENXPKI_UI_KEY_ALG_RSA
# I18N_OPENXPKI_UI_KEY_ALG_EC
# I18N_OPENXPKI_UI_KEY_ALG_DSA
# I18N_OPENXPKI_UI_KEY_ENC
# I18N_OPENXPKI_UI_KEY_ENC_AES256
# I18N_OPENXPKI_UI_KEY_ENC_3DES
# I18N_OPENXPKI_UI_KEY_ENC_IDEA
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH_2048
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH_4096
# I18N_OPENXPKI_UI_KEY_CURVE_NAME
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_PRIME192V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_C2TNB191V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_PRIME239V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_SECT571R1
